micronaut:
  application:
    name: mnBrainstorm
r2dbc:
  datasources:
    default:
      url: r2dbc:h2:mem:///testdb;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password: ''
      schema-generate: CREATE_DROP
      dialect: H2
netty:
  default:
    allocator:
      max-order: 3
